swagger: '2.0'
info:
  title: Web Scraping Hub
  description: Collection of APIs to perform web scraping as a service
  version: 1.0.0
schemes:
  - https
paths:
  /websites:
    post:
      summary: Create a new website
      operationId: createWebsite
      consumes:
        - application/json
      produces:
        - application/json
      x-google-backend:
        address: https://southamerica-east1-web-scraping-hub.cloudfunctions.net/create-website
      parameters:
        - in: body
          name: website
          description: Data of the website to be created
          required: true
          schema:
            $ref: '#/definitions/Website'
      responses:
        '201':
          description: Website created successfully
          schema:
            $ref: '#/definitions/Website'
security:
  - apiKey: []
definitions:
  Website:
    type: object
    properties:
      title:
        type: string
        description: Title of the website
      createdAt:
        type: string
        format: date-time
        description: Date and time of website creation
      updatedAt:
        type: string
        format: date-time
        description: Date and time of website update
securityDefinitions:
  apiKey:
    type: apiKey
    name: X-API-Key
    in: header
