name: Deploy Google Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Authenticate with Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY  }}'
          project_id: '${{ secrets.GCP_PROJECT_ID }}'
      
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Deploy the function to Google Cloud Functions
        run: |
          cd create-website        
          gcloud functions deploy create-website \
            --gen2 \
            --runtime go121 \
            --trigger-http \
            --entry-point CreateWebsite \
            --region southamerica-east1 \
            --memory 256MB \
            --no-allow-unauthenticated \
            --max-instances 1
          cd .. 
        env:
          GOOGLE_APPLICATION_CREDENTIALS: '${{ secrets.GCP_SA_KEY }}'
          PROJECT_ID: '${{ secrets.GCP_PROJECT_ID }}'
