name: Deploy Google Cloud Function

on:
  push:
    branches:
      - main  # Substitua pelo nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar ambiente Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Configure as credenciais do Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Implante a função no Google Cloud Functions
        run: |        
          gcloud functions deploy create-website \
            --gen2 \
            --runtime go121 \
            --trigger-http \
            --entry-point CreateWebsite \
            --allow-unauthenticated \
            --region southamerica-east1 \
            --memory 256MB \
            --max-instances 1 
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

