name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy create-website function
        run: |
          cd create-website
          firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}"
          cd ..
