swagger: '2.0'
info:
  title: Web Scraping Hub
  description: Collection of apis to perform web scraping as a service
  version: 1.0.0
schemes:
  - https
paths:
  /create-website:
    post:
      summary: Cria um novo website
      operationId: createWebsite
      consumes:
        - application/json
      produces:
        - application/json
      x-google-backend:
        address:  https://southamerica-east1-web-scraping-hub.cloudfunctions.net/create-website
      parameters:
        - in: body
          name: website
          description: Dados do website a ser criado
          required: true
          schema:
            $ref: '#/definitions/Website'
      responses:
        '201':
          description: Website criado com sucesso
          schema:
            $ref: '#/definitions/Website'
security:
  - apiKey: []
definitions:
  Website:
    type: object
    properties:
      title:
        type: string
        description: Título do website
      createdAt:
        type: string
        format: date-time
        description: Data e hora de criação do website
      updatedAt:
        type: string
        format: date-time
        description: Data e hora de atualização do website
securityDefinitions: 
  apiKey:
    type: apiKey
    name: X-API-Key
    in: header
